baseURL: "https://www.geeqla.com"
title: Geeqla
paginate: 1
theme: PaperMod
disableHugoGeneratorInject: true
enableInlineShortcodes: true
enableRobotsTXT: true
googleAnalytics: G-3DYJCT1PQ7
enableEmoji: true
disableKinds: ["taxonomy"] # overrules and disables taxonomies at the bottom
ignoreErrors: ["error-disable-taxonomy"] # overrules and disables taxonomies at the bottom

minify:
  minifyOutput: true
  tdewolff:
    html:
      keepComments: false
      keepConditionalComments: false
      keepDefaultAttrVals: true
      keepDocumentTags: true
      keepEndTags: true
      keepQuotes: true
      keepWhitespace: false

languages:
  en:
    languageName: ":gb:"
    weight: 1
    author: Geeqla
    title: House of Geeqla
    # custom params for each language should be under [langcode].parms - hugo v0.120.0
    params:
      languageAltTitle: "English" # added by Geeqla
      description: "House of Geeqla on the Internet."
      label:
        text: Geeqla
        iconHeight: 30
      homeInfoParams:
        Title: Hey!
        Content: >
          My [PGP key](https://geeq.la/@).
      profileMode:
        enabled: true
        title: Hey!
        imageUrl: "icon.svg"
        imageTitle: Geeqla
        imageWidth: 120
        imageHeight: 120
        subtitle: "My **[PGP key](https://geeq.la/@)**."

  de:
    languageName: ":de:"
    weight: 2
    author: Geeqla
    title: Das Haus von Geeqla
    # custom params for each language should be under [langcode].parms - hugo v0.120.0
    params:
      languageAltTitle: "Deutsch" # added by Geeqla
      description: "Das Haus von Geeqla im Internet."
      label:
        text: Geeqla
        iconHeight: 30
      homeInfoParams:
        Title: Hallo!
        Content: >
          Mein [PGP-Schlüssel](https://geeq.la/@).
      profileMode:
        enabled: true
        title: Hallo!
        imageUrl: "icon.svg"
        imageTitle: Geeqla
        imageWidth: 120
        imageHeight: 120
        subtitle: "Mein **[PGP-Schlüssel](https://geeq.la/@)**."

  fr:
    languageName: ":fr:"
    weight: 3
    author: Geeqla
    title: La maison de Geeqla
    # custom params for each language should be under [langcode].parms - hugo v0.120.0
    params:
      languageAltTitle: "Française" # added by Geeqla
      description: "La maison de Geeqla sur le Web."
      label:
        text: Geeqla
        iconHeight: 30
      homeInfoParams:
        Title: Salut!
        Content: >
          Ma [clé publique PGP](https://geeq.la/@).
      profileMode:
        enabled: true
        title: Salut!
        imageUrl: "icon.svg"
        imageTitle: Geeqla
        imageWidth: 120
        imageHeight: 120
        subtitle: "Ma **[clé publique PGP](https://geeq.la/@)**."

params:
  defaultTheme: auto
  # disableThemeToggle: true
  ShowReadingTime: false
  ShowShareButtons: false
  displayFullLangName: true
  mirrorSite: "https://www.geeqla.ru" # added by Geeqla
  mirrorSiteLang: "ru" # added by Geeqla
  mirrorSiteLanguageName: ":ru:" # added by Geeqla
  mirrorSiteLanguageAltTitle: "Русский" # added by Geeqla
  launchYear: 2016 # added by Geeqla
  images: ["website-cover.png"]
  socialIcons:
    - name: github
      url: "https://www.github.com/geeqla"
    - name: linkedin
      url: "https://www.linkedin.com/in/geeqla"
    - name: keybase
      url: "https://keybase.io/geeqla"
    - name: x
      url: "https://www.x.com/geeqla"
    - name: mastodon
      url: "https://mastodon.social/@geeqla"
    - name: instagram
      url: "https://www.instagram.com/geeqla"
    - name: facebook
      url: "https://www.facebook.com/geeqla"
    - name: threads
      url: "https://www.threads.net/geeqla"
    - name: youtube
      url: "https://www.youtube.com/geeqla"
  assets:
    disableHLJS: true # disables loading of highlight.js
    theme_color: "#000000"
    msapplication_TileColor: "#000000"

taxonomies:
  category: categories
  tag: tags
  series: series